apiVersion: v1
kind: Service
metadata:
  name: arablinetours-website
  labels:
    app: arablinetours-website
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: arablinetours-website
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arablinetours-website-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - arablinetours.com
    - www.arablinetours.com
    secretName: arablinetours-tls
  rules:
  - host: arablinetours.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: arablinetours-website
            port:
              number: 80
  - host: www.arablinetours.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: arablinetours-website
            port:
              number: 80
