apiVersion: v1
kind: Service
metadata:
  name: arablinetours-website
  labels:
    app: arablinetours-website
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: arablinetours-website
---
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: arablinetours-website

